spring.datasource.url=jdbc:mysql://localhost:3306/example05
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=YOUR_MYSQL_PASSWORD
# Nhập password MySQL của bạn vào dòng trên

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.open-in-view=false

logging.level.org.springframework.security=debug

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# JWT Security Key
jwt_secret=YOUR_JWT_SECRET_KEY

# Swagger Config
springdoc.swagger-ui.operationsSorter=alpha
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.doc-expansion=false

# Đường dẫn thư mục lưu ảnh sản phẩm (tự động tạo folder tên 'images' trong project)
project.image=images/

# [QUAN TRỌNG] CẤU HÌNH ĐỂ ĐIỆN THOẠI KẾT NỐI ĐƯỢC
# ==========================================
server.port=8080
server.address=0.0.0.0

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=YOUR_GMAIL@gmail.com
spring.mail.password=YOUR_GMAIL_APP_PASSWORD
# (Lưu ý: Đây là App Password, không phải mật khẩu đăng nhập Gmail thường)
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

